sudo: false
language: haskell

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

matrix:
  include:
    - ghc: 8.6.4
      env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - travis_wait 60 stack --no-terminal --system-ghc test --only-snapshot

script:
  - stack --no-terminal --system-ghc test --pedantic

env:
  global:
    secure: p4viJPiZUbANBNWynxsHERHnofPaZgrhmZEMZrsocWNV0snrRpYOoFogL1G2WQ7LJH2eMAfWUuwL0kCqoPOu4fiXXliG6h/zL8uKGgikOZ96C4oCptuOG/Ew117Hj1Ao9cp+9hieu4IADjORe7/BtCcpqDTV2kG7No0+O6bano1Ws+X6IVfrMHHB0DfUNqz9nfg6u3+6wAnPqh3AWOTULIdcV+eq2HD3+iBpR+laPiTATQayDMjC8FYWMVr8NsS07Z0I/jYBN1/lhvRH27beH02CzXpqaEcNn8yfuX6bKEPdjOtdPbl01YHBCnBtZpiluDuwj7a7ITDLqhsQ6pA5iduKQthOX75mooyhwQCEhH0KqlwysOT37k9Q4b/DMQAG6cuwyhZrAtXSprDQVDGgOr72RSUDwkiYmORpTno1VWGFg1ToOVPIN2Rel2HEyb/M/SVozV8lmSZ5D+CvomRg7H6SqCxBi8jP1MsRRBeZ1bBXolfVL7+OR2T4d8zmluDJwOrtQ4zfI/mbnvBg91N4fDY4ibdF/fCDav3/I5timmfyqRCGOVzWlhIovbKwo0OYj3xd9q7SP/EL4Xg8IcZedQF8/viCsltWcceLPBKL63eI9XUbk5enB1WDsDMIae7IUAuUjJ9JmX1XzNiSwG+omD+OCLZbh4UUAS3SngZK4KQ=
